function refreshBattleSelects(){const mine=currentPlan.filter(n=>teamNames.includes(n));document.querySelector('#myActive').innerHTML=mine.map(n=>`<option>${n}</option>`).join('');const opp=selectedOpp.length?selectedOpp:ROSTER.slice(0,8).map(x=>x.name);document.querySelector('#oppActive').innerHTML=opp.map(n=>`<option>${n}</option>`).join('');const strip=document.querySelector('#battlePlanStrip');if(strip)strip.innerHTML=mine.map((n,i)=>`<div class="plan-chip"><span>${i===0?'先発':i===1?'2番手':'ラスト'}</span><b>${n}</b></div>`).join('')}
function moveEffect(move,target){let e=eff(move.type,target.types);if(move.freezeDry&&target.types.includes('Water'))e=Math.max(e,2);return e}
function moveScore(m,mv,foe,state){if(mv.kind==='attack'){let e=moveEffect(mv,foe),stab=m.types.includes(mv.type)?1.5:1,p=mv.power||70;if(mv.hex&&state.foeStatus)p*=2;let score=40+Math.log2(Math.max(.25,e))*17+(p*stab)/4; if(mv.priority&&state.foeLikelyAttack)score+=state.foeHp<=40?20:7;if(mv.selfBoost)score+=6;if(mv.kind==='pivot')score+=4;if(state.foeHp<30&&e>=1)score+=8;return score}
 if(mv.kind==='veil')return state.veil?8:state.snow?94:72;if(mv.kind==='heal')return state.myHp<35?91:state.myHp<60?72:30;if(mv.kind==='boost')return state.foeHp>65&&state.myHp>55?73:42;if(mv.kind==='burn')return foe.style==='physical'?86:51;if(mv.kind==='rocks')return state.rocks?10:68;if(mv.kind==='encore')return state.oppBoost>0?82:55;if(mv.kind==='pivot')return 67;return 48}
function switchScore(target,foe,state){let incoming=resistScore(target.types,foe.types),s=62+(incoming<1?18:incoming>=4?-32:incoming>=2?-18:2)+target.bulk*.08; if(target.name==='ラウドボーン'&&state.oppBoost>0)s+=29;if(target.name==='ドドゲザン'&&state.foeHp<=35)s+=17;if(target.name==='カイリュー'&&state.veil)s+=10;if(target.name==='アローラキュウコン'&&!state.veil)s+=6;return s}
function battleState(){return {myHp:+document.querySelector('#myHp').value,foeHp:+document.querySelector('#oppHp').value,myBoost:+document.querySelector('#myBoost').value,oppBoost:+document.querySelector('#oppBoostLevel').value,veil:document.querySelector('#veil').checked,snow:document.querySelector('#snow').checked,rocks:document.querySelector('#rocks').checked,foeStatus:document.querySelector('#foeStatus').checked,foeLikelyAttack:document.querySelector('#foeLikelyAttack').checked}}
function analyzeBattle(){const m=mon(document.querySelector('#myActive').value),foe=mon(document.querySelector('#oppActive').value),st=battleState();let acts=m.moves.map(mv=>({title:mv.name,score:moveScore(m,mv,foe,st),desc:moveDesc(mv,m,foe,st)}));for(const n of currentPlan.filter(x=>x!==m.name)){const t=mon(n);acts.push({title:`${n}へ交代`,score:switchScore(t,foe,st),desc:switchDesc(t,foe,st)})}acts.sort((a,b)=>b.score-a.score);const top=acts.slice(0,4),max=Math.max(...top.map(x=>x.score));document.querySelector('#actions').innerHTML=top.map((x,i)=>`<div class="action"><div class="action-top"><strong>${i+1}. ${x.title}</strong><span class="pct">${Math.round(clamp(45+x.score/max*50,0,99))}</span></div><div class="desc">${x.desc}</div></div>`).join('');return top}
function moveDesc(mv,m,foe,st){if(mv.kind==='attack'){const e=moveEffect(mv,foe);let t=e>=4?'4倍級':e>=2?'弱点':e===0?'無効':e<1?'半減以下':'等倍';return `${t}。威力${mv.power||'-'}、${m.types.includes(mv.type)?'STABあり':'STABなし'}。${mv.priority?'先制技なので終盤価値が高い。':''}${mv.hex&&st.foeStatus?'状態異常でたたりめ強化。':''}`}
 const map={veil:'後続の被ダメージを抑え、カイリューやドドゲザンの行動回数を増やす。',heal:'HPを戻して行動回数を確保。',boost:'相手に即時の大打点がなければ、以降の抜き性能を上げる。',burn:'物理相手の火力を落として受けやすくする。',rocks:'交代への継続的な圧力を作る。',encore:'積み技・補助技を固定できれば一気に有利になる。',utility:'盤面を崩す補助択。',pivot:'攻撃しながら有利対面を作る。'};return map[mv.kind]||'役割に沿った補助択。'}
function switchDesc(t,foe,st){const e=resistScore(t.types,foe.types);let d=e<1?'相手の主要タイプを受けやすい。':e>=2?'弱点を突かれる可能性があるので読みが必要。':'等倍中心で受ける交代。';if(t.name==='ラウドボーン'&&st.oppBoost>0)d+=' てんねん枠として積み相手に特に有効。';if(t.name==='ドドゲザン'&&st.foeHp<=35)d+=' 終盤ならふいうち圏内を狙える。';return d}
