function renderMyCards(){document.querySelector('#myTeamCards').innerHTML=teamNames.map(n=>card(mon(n))).join('')}
function renderOpp(q=''){const list=ROSTER.filter(m=>m.name.includes(q)).slice(0,48);document.querySelector('#oppPool').innerHTML=list.map(m=>{const i=selectedOpp.findIndex(x=>x===m.name);return card(m,i>=0,i>=0?i+1:null)}).join('');document.querySelectorAll('#oppPool .card').forEach(e=>e.onclick=()=>toggleOpp(e.dataset.name));document.querySelector('#oppCount').textContent=selectedOpp.length;const mc=document.querySelector('#mobileOppCount');if(mc)mc.textContent=selectedOpp.length+'/6';const strip=document.querySelector('#selectedOppStrip');if(strip)strip.innerHTML=selectedOpp.length?selectedOpp.map((n,i)=>`<button class="selected-chip" data-name="${n}">${i+1}. ${n}<span class="x">×</span></button>`).join(''):'<span class="meta">選んだ相手がここに並びます</span>';if(strip)strip.querySelectorAll('.selected-chip').forEach(e=>e.onclick=()=>toggleOpp(e.dataset.name));refreshBattleSelects()}
function toggleOpp(n){const i=selectedOpp.indexOf(n);if(i>=0)selectedOpp.splice(i,1);else if(selectedOpp.length<6)selectedOpp.push(n);else alert('相手は6体までです');renderOpp(document.querySelector('#oppSearch').value.trim())}

function attackCoverage(m,foes){return avg(foes.map(f=>{const target=mon(f);let best=1;for(const mv of m.moves.filter(x=>x.kind==='attack')){let e=eff(mv.type,target.types);if(mv.freezeDry&&target.types.includes('Water'))e=Math.max(2,e);const stab=m.types.includes(mv.type)?1.5:1;best=Math.max(best,e*stab*(mv.power||70)/85)}return clamp(best,0,4)}))}
function defenseFit(m,foes){return avg(foes.map(f=>{const fm=mon(f);const e=resistScore(m.types,fm.types);return e>=4?-18:e>=2?-9:e<1?7:1}))}
function matchupScore(m,foes){let s=48+attackCoverage(m,foes)*12+defenseFit(m,foes)+m.speed*.05+m.bulk*.03;
  if(m.role.includes('壁'))s+=11;
  if(m.role.includes('積み対策'))s+=foes.filter(f=>['カイリュー','ガブリアス','ギャラドス','ミミッキュ','ドドゲザン','セグレイブ','コノヨザル'].includes(f)).length*4;
  if(m.role.includes('終盤'))s+=7;
  if(m.role.includes('高速'))s+=foes.filter(f=>mon(f).speed>=90).length*1.8;
  return s}
function pairSynergy(a,b){let s=0;if(a.role.includes('壁')&&(b.role.includes('エース')||b.role.includes('終盤')||b.role.includes('崩し')))s+=10;if(a.style!==b.style)s+=2;const shared=a.types.filter(t=>b.types.includes(t)).length;s-=shared*2;return s}
function combinations(arr,k,start=0,p=[],out=[]){if(p.length===k){out.push(p.slice());return out}for(let i=start;i<arr.length;i++){p.push(arr[i]);combinations(arr,k,i+1,p,out);p.pop()}return out}
function perms(a){if(a.length<=1)return[a];let out=[];for(let i=0;i<a.length;i++){const rest=a.slice(0,i).concat(a.slice(i+1));for(const p of perms(rest))out.push([a[i],...p])}return out}
function orderScore(order,foes){let s=0;const [lead,mid,last]=order.map(mon);s+=matchupScore(lead,foes)*.45+matchupScore(mid,foes)*.33+matchupScore(last,foes)*.31;s+=pairSynergy(lead,mid)+pairSynergy(mid,last);
 if(lead.role.includes('壁')||lead.role.includes('先発')||lead.role.includes('高速対面'))s+=10;if(last.role.includes('終盤'))s+=12;if(mid.role.includes('エース'))s+=7;
 if(lead.name==='アローラキュウコン'&&mid.name==='カイリュー')s+=10;if(last.name==='ドドゲザン')s+=8;return s}
function analyzeSelection(){if(selectedOpp.length<3){alert('相手を3体以上選んでください');return}const combos=combinations(teamNames,3);let plans=[];for(const c of combos){for(const p of perms(c))plans.push({order:p,score:orderScore(p,selectedOpp)})}plans.sort((a,b)=>b.score-a.score);const unique=[];for(const p of plans){const key=p.order.slice().sort().join('|');if(!unique.some(x=>x.key===key)){unique.push({...p,key});if(unique.length===3)break}}currentPlan=unique[0].order.slice();renderPlans(unique);refreshBattleSelects();const r=document.querySelector('#selectResults');r.classList.remove('hidden');STORE.setItem('cbc_last_opp_v02',JSON.stringify(selectedOpp));STORE.setItem('cbc_last_plan_v02',JSON.stringify(currentPlan));setTimeout(()=>r.scrollIntoView({behavior:'smooth',block:'start'}),40)}
function planReasons(p){const [a,b,c]=p.order.map(mon),r=[];if(a.role.includes('壁'))r.push('先発で壁を作り、裏2体の行動回数を増やす。');if(a.role.includes('先発'))r.push('先発性能が高く、初手から相手に圧力を掛けられる。');if(b.role.includes('エース'))r.push('中盤はエースで削りと崩しを担当。');if(c.role.includes('終盤'))r.push('終盤の先制技・詰め性能を最後に温存。');if(p.order.includes('ラウドボーン'))r.push('積み展開へのストッパーを確保。');return r.join(' ')||'タイプ相性と役割分担の総合点が高い選出。'}
function biggestThreats(order){return selectedOpp.map(f=>{const fm=mon(f);const best=Math.min(...order.map(n=>resistScore(mon(n).types,fm.types)));return {n:f,v:best}}).sort((a,b)=>b.v-a.v).slice(0,3).filter(x=>x.v>=2)}
function renderPlans(plans){const max=plans[0].score;document.querySelector('#plans').innerHTML=plans.map((p,idx)=>{const threat=biggestThreats(p.order);return `<div class="result"><div class="result-head"><strong>${idx===0?'本命':'代替'}プラン ${idx+1}</strong><span class="grade">${Math.round(100*p.score/max)}点</span></div><div class="order">${p.order.map((n,i)=>`<div class="pick"><div class="k">${i===0?'先発':i===1?'2番手':'ラスト'}</div><b>${n}</b><div class="scorebar"><div style="width:${clamp(matchupScore(mon(n),selectedOpp),20,100)}%"></div></div></div>`).join('')}</div><div class="reason">${planReasons(p)}</div>${threat.length?`<div class="threats">${threat.map(x=>`<span class="pill warn">注意：${x.n}</span>`).join('')}</div>`:''}<div class="controls"><button class="btn ${idx===0?'primary':'ghost'} small use-plan" data-plan="${p.order.join('|')}">${idx===0?'この選出でバトルへ':'このプランでバトルへ'}</button></div></div>`}).join('');document.querySelectorAll('.use-plan').forEach(b=>b.onclick=()=>{currentPlan=b.dataset.plan.split('|');refreshBattleSelects();switchTab('battle');window.scrollTo({top:0,behavior:'smooth'});setTimeout(analyzeBattle,60)})}
