function renderTeamEditor(){document.querySelector('#teamEditor').innerHTML=teamNames.map((n,i)=>`<div class="team-slot"><div class="field"><label>スロット ${i+1}</label><select class="team-select" data-i="${i}">${ROSTER.map(m=>`<option ${m.name===n?'selected':''}>${m.name}</option>`).join('')}</select></div><div class="field"><label>役割</label><div class="role">${mon(n).role}</div></div><div class="field"><label>持ち物 / 特性</label><div class="meta">${mon(n).item||'未設定'}<br>${mon(n).ability||'未設定'}</div></div></div>`).join('');document.querySelectorAll('.team-select').forEach(s=>s.onchange=()=>{const i=+s.dataset.i;const n=s.value;if(teamNames.includes(n)&&teamNames[i]!==n){alert('同じポケモンは重複できません');s.value=teamNames[i];return}teamNames[i]=n;renderTeamEditor();renderTeamBalance()})}
function renderTeamBalance(){const ms=teamNames.map(mon),physical=ms.filter(x=>x.style==='physical').length,special=ms.filter(x=>x.style==='special').length,mixed=ms.filter(x=>x.style==='mixed').length,fast=ms.filter(x=>x.speed>=85).length,bulky=ms.filter(x=>x.bulk>=85).length,support=ms.filter(x=>['壁展開','サポート','物理受け・積み対策','受け・対面操作'].includes(x.role)).length;document.querySelector('#teamBalance').innerHTML=`<div class="statrow"><div class="stat"><b>${physical}/${special}/${mixed}</b><span>物理 / 特殊 / 両刀</span></div><div class="stat"><b>${fast}</b><span>高速枠</span></div><div class="stat"><b>${bulky}</b><span>高耐久枠</span></div></div><div class="reason">${physical>=4?'物理寄り。特殊崩しを追加すると受けに強くなります。 ':''}${special>=4?'特殊寄り。物理崩しが欲しいです。 ':''}${fast<2?'高速枠が少なめ。スカーフや高速アタッカーが候補。 ':''}${support<1?'サポート・受け枠が薄めです。 ':''}${fast>=2&&bulky>=1?'速度と耐久のバランスは良好。':''}</div>`}
function saveTeam(){STORE.setItem('cbc_team_v02',JSON.stringify(teamNames));renderMyCards();renderOpp();currentPlan=teamNames.slice(0,3);refreshBattleSelects();alert('チームを保存しました')}

function scoutScore(c){const team=teamNames.map(mon);let s=50,why=[],fast=team.filter(x=>x.speed>=90).length,special=team.filter(x=>x.style==='special').length,physical=team.filter(x=>x.style==='physical').length,bulky=team.filter(x=>x.bulk>=88).length;
 if(c.speed>=90&&fast<2){s+=16;why.push('高速枠を補える')}if(c.style==='special'&&special<2){s+=13;why.push('特殊火力を補える')}if(c.style==='physical'&&physical<2){s+=13;why.push('物理火力を補える')}if(c.bulk>=88&&bulky<2){s+=11;why.push('耐久枠を増やせる')}if(c.role.includes('受け')&&!team.some(x=>x.role.includes('受け'))){s+=12;why.push('受け性能を補完')}
 const ownTypes=new Set(team.flatMap(x=>x.types));const newTypes=c.types.filter(t=>!ownTypes.has(t));s+=newTypes.length*6;if(newTypes.length)why.push(`${newTypes.join('/')}打点・耐性を追加`);
 if(c.name==='サーフゴー'){s+=8;why.push('特殊崩しと鋼枠を同時に確保')}if(c.name==='テツノツツミ'||c.name==='ハバタクカミ'){s+=6;why.push('高速特殊の別勝ち筋')}if(c.name==='ヘイラッシャ'){s+=5;why.push('物理エースへの保険')};return {score:clamp(Math.round(s),0,99),why}}
function renderScout(q=''){const list=ROSTER.filter(m=>!teamNames.includes(m.name)&&m.name.includes(q)).sort((a,b)=>scoutScore(b).score-scoutScore(a).score).slice(0,36);document.querySelector('#scoutPool').innerHTML=list.map(m=>{const s=scoutScore(m);return `<div class="card click" data-name="${m.name}"><div class="name">${m.name}</div><div class="types">${typeLabel(m.types)}</div><div class="role">${m.role}</div><div class="meta">適性 ${s.score}点</div></div>`}).join('');document.querySelectorAll('#scoutPool .card').forEach(e=>e.onclick=()=>showScout(e.dataset.name))}
function showScout(n){const c=mon(n),r=scoutScore(c),weak=[];for(const t of TYPES){if(eff(t,c.types)>=2)weak.push(t)}document.querySelector('#scoutDetail').innerHTML=`<div class="two"><div class="result"><div class="scout-score">${r.score}<span style="font-size:15px"> / 100</span></div><div class="scout-sub">${c.name} のチーム適性</div><div class="reason">${r.why.join('。')}。</div></div><div class="result"><b>${c.role}</b><div class="move-list">${c.moves.map(x=>x.name).join(' / ')}</div><div class="threats">${c.types.map(x=>`<span class="pill">${x}</span>`).join('')}</div><div class="delta">速さ ${c.speed} · 耐久 ${c.bulk}</div><div class="meta">主な弱点: ${weak.slice(0,6).join(' / ')||'少ない'}</div></div></div>`;document.querySelector('#scoutResult').classList.remove('hidden')}
